# By convention, the first pseudorule should be called "all"
# We're using the expand() function to create multiple targets
rule all:
	input:
		expand(
			"{greeting}/world.txt",
			greeting = ['hello1', 'hola1'],
		),

# First real rule, this is using a wildcard called "greeting"
rule hello_world:
	output:
		"{greeting}/world.txt",
	resources: 
		kueue_operator="job"
	shell:
		"""
		mkdir -p "{wildcards.greeting}"
		echo "{wildcards.greeting}, World!" > {output}
		"""